# Generated by Django 3.2 on 2021-04-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gov_thai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date', models.TimeField()),
                ('FirstPrize', models.CharField(max_length=20)),
                ('ThreeFront', models.CharField(max_length=20)),
                ('ThreeUnder', models.CharField(max_length=20)),
                ('TwoUnder', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'gov_thai',
                'verbose_name_plural': 'gov_thai',
            },
        ),
    ]
