# Generated by Django 3.2 on 2021-04-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gov_thai',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
