# Generated by Django 3.2 on 2021-04-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoAPI', '0002_alter_gov_thai_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='lao_lotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('Four', models.CharField(max_length=20)),
                ('Three', models.CharField(max_length=20)),
                ('Two', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='lao_star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('FourTop', models.CharField(max_length=20)),
                ('ThreeTop', models.CharField(max_length=20)),
                ('TwoTop', models.CharField(max_length=20)),
                ('TwoUnder', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='lao_vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('Five', models.CharField(max_length=20)),
                ('Four', models.CharField(max_length=20)),
                ('Three', models.CharField(max_length=20)),
                ('Two', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
