# Generated by Django 3.2 on 2021-04-11 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lottoAPI', '0003_lao_lotto_lao_star_lao_vip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gov_thai',
            options={},
        ),
        migrations.AddField(
            model_name='gov_thai',
            name='ThreeFrontTwo',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gov_thai',
            name='ThreeUnderTwo',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gov_thai',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
